# Plagiarism Detection Model

Now that you've created training and test data, you are ready to define and train a model. Your goal in this notebook, will be to train a binary classification model that learns to label an answer file as either plagiarized or not, based on the features you provide the model.

This task will be broken down into a few discrete steps:

* Upload your data to S3.
* Define a binary classification model and a training script.
* Train your model and deploy it.
* Evaluate your deployed classifier and answer some questions about your approach.

To complete this notebook, you'll have to complete all given exercises and answer all the questions in this notebook.
> All your tasks will be clearly labeled **EXERCISE** and questions as **QUESTION**.

It will be up to you to explore different classification models and decide on a model that gives you the best performance for this dataset.

---

## Load Data to S3

In the last notebook, you should have created two files: a `training.csv` and `test.csv` file with the features and class labels for the given corpus of plagiarized/non-plagiarized text data. 

>The below cells load in some AWS SageMaker libraries and creates a default bucket. After creating this bucket, you can upload your locally stored data to S3.

Save your train and test `.csv` feature files, locally. To do this you can run the second notebook "2_Plagiarism_Feature_Engineering" in SageMaker or you can manually upload your files to this notebook using the upload icon in Jupyter Lab. Then you can upload local files to S3 by using `sagemaker_session.upload_data` and pointing directly to where the training data is saved.

In [1]:
import pandas as pd
import boto3
import sagemaker

In [2]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

## EXERCISE: Upload your training data to S3

Specify the `data_dir` where you've saved your `train.csv` file. Decide on a descriptive `prefix` that defines where your data will be uploaded in the default S3 bucket. Finally, create a pointer to your training data by calling `sagemaker_session.upload_data` and passing in the required parameters. It may help to look at the [Session documentation](https://sagemaker.readthedocs.io/en/stable/session.html#sagemaker.session.Session.upload_data) or previous SageMaker code examples.

You are expected to upload your entire directory. Later, the training script will only access the `train.csv` file.

In [11]:
import os

# should be the name of directory you created to save your features data
data_dir = 'plagiarism_data'

# set prefix, a descriptive name for a directory  
prefix = 'plagiarism_project'

# upload all data to S3

train_location = sagemaker_session.upload_data(
    path=os.path.join(data_dir, 'train.csv'),
    bucket=bucket,
    key_prefix=prefix
)
test_location = sagemaker_session.upload_data(
    path=os.path.join(data_dir, 'test.csv'),
    bucket=bucket,
    key_prefix=prefix
)

### Test cell

Test that your data has been successfully uploaded. The below cell prints out the items in your S3 bucket and will throw an error if it is empty. You should see the contents of your `data_dir` and perhaps some checkpoints. If you see any other files listed, then you may have some old model files that you can delete via the S3 console (though, additional files shouldn't affect the performance of model developed in this notebook).

In [12]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# confirm that data is in S3 bucket
empty_check = []
for obj in boto3.resource('s3').Bucket(bucket).objects.all():
    empty_check.append(obj.key)
    print(obj.key)

assert len(empty_check) !=0, 'S3 bucket is empty.'
print('Test passed!')

plagiarism_project/test.csv
plagiarism_project/train.csv
pytorch-inference-2020-03-16-14-08-29-039/model.tar.gz
pytorch-training-2020-03-16-13-56-20-201/source/sourcedir.tar.gz
sagemaker/moon-data/.ipynb_checkpoints/train-checkpoint.csv
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/debug-output/collections/000000000/worker_0_collections.json
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/debug-output/events/000000000000/000000000000_worker_0.tfevents
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/debug-output/events/000000000500/000000000500_worker_0.tfevents
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/debug-output/index/000000000/000000000000_worker_0.json
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/debug-output/index/000000000/000000000500_worker_0.json
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/debug-output/training_job_end.ts
sagemaker/moon-data/pytorch-training-2020-03-16-13-56-20-201/ou

---

# Modeling

Now that you've uploaded your training data, it's time to define and train a model!

The type of model you create is up to you. For a binary classification task, you can choose to go one of three routes:
* Use a built-in classification algorithm, like LinearLearner.
* Define a custom Scikit-learn classifier, a comparison of models can be found [here](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html).
* Define a custom PyTorch neural network classifier. 

It will be up to you to test out a variety of models and choose the best one. Your project will be graded on the accuracy of your final model. 
 
---

## EXERCISE: Complete a training script 

To implement a custom classifier, you'll need to complete a `train.py` script. You've been given the folders `source_sklearn` and `source_pytorch` which hold starting code for a custom Scikit-learn model and a PyTorch model, respectively. Each directory has a `train.py` training script. To complete this project **you only need to complete one of these scripts**; the script that is responsible for training your final model.

A typical training script:
* Loads training data from a specified directory
* Parses any training & model hyperparameters (ex. nodes in a neural network, training epochs, etc.)
* Instantiates a model of your design, with any specified hyperparams
* Trains that model 
* Finally, saves the model so that it can be hosted/deployed, later

### Defining and training a model
Much of the training script code is provided for you. Almost all of your work will be done in the `if __name__ == '__main__':` section. To complete a `train.py` file, you will:
1. Import any extra libraries you need
2. Define any additional model training hyperparameters using `parser.add_argument`
2. Define a model in the `if __name__ == '__main__':` section
3. Train the model in that same section

Below, you can use `!pygmentize` to display an existing `train.py` file. Read through the code; all of your tasks are marked with `TODO` comments. 

**Note: If you choose to create a custom PyTorch model, you will be responsible for defining the model in the `model.py` file,** and a `predict.py` file is provided. If you choose to use Scikit-learn, you only need a `train.py` file; you may import a classifier from the `sklearn` library.

In [5]:
# directory can be changed to: source_sklearn or source_pytorch
!pygmentize source_sklearn/train.py

from __future__ import print_function

import argparse
import os
import pandas as pd

from sklearn.externals import joblib

## TODO: Import any additional libraries you need to define a model


# Provided model load function
def model_fn(model_dir):
    """Load model from the model_dir. This is the same model that is saved
    in the main if statement.
    """
    print("Loading model.")
    
    # load using joblib
    model = joblib.load(os.path.join(model_dir, "model.joblib"))
    print("Done loading model.")
    
    return model


## TODO: Complete the main code
if __name__ == '__main__':
    
    # All of the model parameters and training parameters are sent as arguments
    # when this script is executed, during a training job
    
    # Here we set up an argument parser to easily access the parameters
    parser = argparse.ArgumentParser()

    # SageMaker parameters, like the directories for training data and saving models; set automatically
    # Do not need to change
    par

### Provided code

If you read the code above, you can see that the starter code includes a few things:
* Model loading (`model_fn`) and saving code
* Getting SageMaker's default hyperparameters
* Loading the training data by name, `train.csv` and extracting the features and labels, `train_x`, and `train_y`

If you'd like to read more about model saving with [joblib for sklearn](https://scikit-learn.org/stable/modules/model_persistence.html) or with [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html), click on the provided links.

---
# Create an Estimator

When a custom model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained; the `train.py` function you specified above. To run a custom training script in SageMaker, construct an estimator, and fill in the appropriate constructor arguments:

* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `source_sklearn` OR `source_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **role**: Role ARN, which was specified, above.
* **train_instance_count**: The number of training instances (should be left at 1).
* **train_instance_type**: The type of SageMaker instance for training. Note: Because Scikit-learn does not natively support GPU training, Sagemaker Scikit-learn does not currently support training on GPU instance types.
* **sagemaker_session**: The session used to train on Sagemaker.
* **hyperparameters** (optional): A dictionary `{'name':value, ..}` passed to the train function as hyperparameters.

Note: For a PyTorch model, there is another optional argument **framework_version**, which you can set to the latest version of PyTorch, `1.0`.

## EXERCISE: Define a Scikit-learn or PyTorch estimator

To import your desired estimator, use one of the following lines:
```
from sagemaker.sklearn.estimator import SKLearn
```
```
from sagemaker.pytorch import PyTorch
```

In [16]:

# your import and estimator code, here

from sagemaker.amazon.amazon_estimator import get_image_uri

container = get_image_uri(sagemaker_session.boto_region_name, 'xgboost', '0.90-1')

xgb = sagemaker.estimator.Estimator(container, # The location of the container we wish to use
                                    role,                                    # What is our current IAM Role
                                    train_instance_count=1,                  # How many compute instances
                                    train_instance_type='ml.m4.xlarge',      # What kind of compute instances
                                    output_path=f's3://{bucket}/{prefix}/xgb-output',
                                    sagemaker_session=sagemaker_session)

xgb.set_hyperparameters(max_depth=10,
                        eta=0.2,
                        gamma=4,
                        min_child_weight=6,
                        subsample=0.8,
                        silent=0,
                        objective='binary:logistic',
                        early_stopping_rounds=10,
                        num_round=500)


from sagemaker.pytorch import PyTorch

py_torch = PyTorch(
    entry_point='train.py',
    source_dir='source_pytorch',
    role=role,
    sagemaker_session=sagemaker_session,
    train_instance_count=1,
    train_instance_type='ml.c4.xlarge',
    output_path=f's3://{bucket}/{prefix}/pytorch-output',
    hyperparameters={
        "input_features": 6,
        "hidden_dim": 30,
        "output_dim": 1,
        "epochs": 200
    },
    framework_version='1.4.0'
)

from sagemaker.sklearn.estimator import SKLearn

sk_learn = SKLearn(
    entry_point='train.py',
    source_dir='source_sklearn',
    role=role,
    sagemaker_session = sagemaker_session,
    train_instance_count=1,
    train_instance_type='ml.c4.xlarge',
    output_path=f's3://{bucket}/{prefix}/sklearn-output',
    hyperparameters={
        "max_depth": 10,
    }
)

## EXERCISE: Train the estimator

Train your estimator on the training data stored in S3. This should create a training job that you can monitor in your SageMaker console.

In [24]:
%%time

# Train your estimator on S3 training data

xgb.fit({
    'train': sagemaker.s3_input(
        s3_data=train_location,
        content_type='csv'
    )})

2020-03-27 19:59:17 Starting - Starting the training job...
2020-03-27 19:59:19 Starting - Launching requested ML instances.........
2020-03-27 20:01:02 Starting - Preparing the instances for training......
2020-03-27 20:02:00 Downloading - Downloading input data...
2020-03-27 20:02:35 Training - Downloading the training image..INFO:sagemaker-containers:Imported framework sagemaker_xgboost_container.training
INFO:sagemaker-containers:Failed to parse hyperparameter objective value binary:logistic to Json.
Returning the value itself
INFO:sagemaker-containers:No GPUs detected (normal if no gpus installed)
INFO:sagemaker_xgboost_container.training:Running XGBoost Sagemaker in algorithm mode
INFO:root:Determined delimiter of CSV input is ','
INFO:root:Determined delimiter of CSV input is ','
[20:02:58] 70x6 matrix with 420 entries loaded from /opt/ml/input/data/train?format=csv&label_column=0&delimiter=,
INFO:root:Single node training.
INFO:root:Train matrix has 70 rows
[0]#011train-error:0

In [17]:
%%time

# Train your estimator on S3 training data

py_torch.fit({'train': train_location})

2020-03-27 19:38:14 Starting - Starting the training job...
2020-03-27 19:38:16 Starting - Launching requested ML instances............
2020-03-27 19:40:23 Starting - Preparing the instances for training...
2020-03-27 19:41:15 Downloading - Downloading input data......
2020-03-27 19:42:05 Training - Downloading the training image..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2020-03-27 19:42:26,845 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2020-03-27 19:42:26,848 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-03-27 19:42:26,860 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2020-03-27 19:42:28,281 sagemaker_pytorch_container.training INFO     Invoking user training script.
2020-03-27 19:42:31,927 sagemaker-containers INFO     Module default_user_module_name does not provide a setup.py. 
Generating setu

In [18]:
%%time

# Train your estimator on S3 training data

sk_learn.fit({'train': train_location})

2020-03-27 19:43:27 Starting - Starting the training job...
2020-03-27 19:43:30 Starting - Launching requested ML instances............
2020-03-27 19:45:41 Starting - Preparing the instances for training......
2020-03-27 19:46:46 Downloading - Downloading input data...
2020-03-27 19:47:10 Training - Downloading the training image.2020-03-27 19:47:30,693 sagemaker-containers INFO     Imported framework sagemaker_sklearn_container.training
2020-03-27 19:47:30,695 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-03-27 19:47:30,705 sagemaker_sklearn_container.training INFO     Invoking user training script.
2020-03-27 19:47:31,058 sagemaker-containers INFO     Module train does not provide a setup.py. 
Generating setup.py
2020-03-27 19:47:31,058 sagemaker-containers INFO     Generating setup.cfg
2020-03-27 19:47:31,058 sagemaker-containers INFO     Generating MANIFEST.in
2020-03-27 19:47:31,059 sagemaker-containers INFO     Installing module with the follow

## EXERCISE: Deploy the trained model

After training, deploy your model to create a `predictor`. If you're using a PyTorch model, you'll need to create a trained `PyTorchModel` that accepts the trained `<model>.model_data` as an input parameter and points to the provided `source_pytorch/predict.py` file as an entry point. 

To deploy a trained model, you'll use `<model>.deploy`, which takes in two arguments:
* **initial_instance_count**: The number of deployed instances (1).
* **instance_type**: The type of SageMaker instance for deployment.

Note: If you run into an instance error, it may be because you chose the wrong training or deployment instance_type. It may help to refer to your previous exercise code to see which types of instances we used.

In [29]:
%%time

# deploy your model to create a predictor
xgb_predictor = xgb.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')


-----------------!CPU times: user 270 ms, sys: 5.39 ms, total: 275 ms
Wall time: 8min 33s


In [27]:
%%time

from sagemaker.pytorch import PyTorchModel

pytorch_model = PyTorchModel(
    model_data=py_torch.model_data,
    entry_point='predict.py',
    source_dir='source_pytorch',
    role=role,
    sagemaker_session=sagemaker_session,
    framework_version='1.4.0'
)

# deploy your model to create a predictor
pytorch_predictor = pytorch_model.deploy(
    initial_instance_count=1,
    instance_type='ml.t2.medium'
)


-------------------!CPU times: user 365 ms, sys: 9.84 ms, total: 375 ms
Wall time: 9min 32s


In [30]:
%%time

# deploy your model to create a predictor
sklearn_predictor = sk_learn.deploy(
    initial_instance_count=1,
    instance_type='ml.t2.medium'
)


---------------!CPU times: user 252 ms, sys: 310 µs, total: 252 ms
Wall time: 7min 32s


---
# Evaluating Your Model

Once your model is deployed, you can see how it performs when applied to our test data.

The provided cell below, reads in the test data, assuming it is stored locally in `data_dir` and named `test.csv`. The labels and features are extracted from the `.csv` file.

In [31]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import os

# read in test data, assuming it is stored locally
test_data = pd.read_csv(os.path.join(data_dir, "test.csv"), header=None, names=None)

# labels are in the first column
test_y = test_data.iloc[:,0]
test_x = test_data.iloc[:,1:]

## EXERCISE: Determine the accuracy of your model

Use your deployed `predictor` to generate predicted, class labels for the test data. Compare those to the *true* labels, `test_y`, and calculate the accuracy as a value between 0 and 1.0 that indicates the fraction of test data that your model classified correctly. You may use [sklearn.metrics](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) for this calculation.

**To pass this project, your model should get at least 90% test accuracy.**

In [33]:
from sagemaker.predictor import csv_serializer
import numpy as np

# We need to tell the endpoint what format the data we are sending is in
xgb_predictor.content_type = 'text/csv'
xgb_predictor.serializer = csv_serializer

# First: generate predicted, class labels
xgb_test_y_preds = np.fromstring(
    xgb_predictor.predict(test_x.values).decode('utf-8'),
    sep=','
)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(xgb_test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [34]:
# First: generate predicted, class labels
pytorch_test_y_preds = np.squeeze(
    np.round(pytorch_predictor.predict(test_x))
)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(pytorch_test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [36]:
# First: generate predicted, class labels
sklearn_test_y_preds = sklearn_predictor.predict(test_x)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(sklearn_test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [38]:
xgb_test_y_preds = np.round(xgb_test_y_preds)
xgb_test_y_preds

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 0.])

In [39]:
# Second: calculate the test accuracy
xgb_accuracy = sum(xgb_test_y_preds == test_y)/len(test_y)

print(xgb_accuracy)


## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(xgb_test_y_preds)
print('\nTrue class labels: ')
print(test_y.values)

1.0

Predicted class labels: 
[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0.
 0.]

True class labels: 
[1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0]


In [41]:
pytorch_test_y_preds

array([1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 0.], dtype=float32)

In [42]:
# Second: calculate the test accuracy
pytorch_accuracy = sum(pytorch_test_y_preds == test_y)/len(test_y)

print(pytorch_accuracy)


## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(pytorch_test_y_preds)
print('\nTrue class labels: ')
print(test_y.values)

1.0

Predicted class labels: 
[1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0.
 0.]

True class labels: 
[1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0]


In [43]:
sklearn_test_y_preds

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1])

In [44]:
# Second: calculate the test accuracy
sklearn_accuracy = sum(sklearn_test_y_preds == test_y)/len(test_y)

print(sklearn_accuracy)


## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(sklearn_test_y_preds)
print('\nTrue class labels: ')
print(test_y.values)

0.88

Predicted class labels: 
[1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 0 1 0 1 1 1 1]

True class labels: 
[1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0]


In [46]:
# code to evaluate the endpoint on test data
# returns a variety of model metrics
def evaluate(test_preds, test_labels, verbose=True):
    """
    Evaluate a model on a test set given the predictions.  
    Return binary classification metrics.
    :param test_preds: The predicted values
    :param test_labels: Class labels for test data
    :param verbose: If True, prints a table of all performance metrics
    :return: A dictionary of performance metrics.
    """
    
    
    # calculate true positives, false positives, true negatives, false negatives
    tp = np.logical_and(test_labels, test_preds).sum()
    fp = np.logical_and(1-test_labels, test_preds).sum()
    tn = np.logical_and(1-test_labels, 1-test_preds).sum()
    fn = np.logical_and(test_labels, 1-test_preds).sum()
    
    # calculate binary classification metrics
    recall = tp / (tp + fn)
    precision = tp / (tp + fp)
    accuracy = (tp + tn) / (tp + fp + tn + fn)
    
    # print metrics
    if verbose:
        print(pd.crosstab(test_labels, test_preds, rownames=['actuals'], colnames=['predictions']))
        print("\n{:<11} {:.3f}".format('Recall:', recall))
        print("{:<11} {:.3f}".format('Precision:', precision))
        print("{:<11} {:.3f}".format('Accuracy:', accuracy))
        print()
        
    return {'TP': tp, 'FP': fp, 'FN': fn, 'TN': tn, 
            'Precision': precision, 'Recall': recall, 'Accuracy': accuracy}

In [47]:
evaluate(sklearn_test_y_preds, test_y, True)

predictions  0   1
actuals           
0            7   3
1            0  15

Recall:     1.000
Precision:  0.833
Accuracy:   0.880



{'TP': 15,
 'FP': 3,
 'FN': 0,
 'TN': 7,
 'Precision': 0.8333333333333334,
 'Recall': 1.0,
 'Accuracy': 0.88}

In [48]:
evaluate(xgb_test_y_preds, test_y, True)

predictions  0.0  1.0
actuals              
0             10    0
1              0   15

Recall:     1.000
Precision:  1.000
Accuracy:   1.000



{'TP': 15,
 'FP': 0,
 'FN': 0,
 'TN': 10,
 'Precision': 1.0,
 'Recall': 1.0,
 'Accuracy': 1.0}

In [49]:
evaluate(pytorch_test_y_preds, test_y, True)

predictions  0.0  1.0
actuals              
0             10    0
1              0   15

Recall:     1.000
Precision:  1.000
Accuracy:   1.000



{'TP': 15,
 'FP': 0,
 'FN': 0,
 'TN': 10,
 'Precision': 1.0,
 'Recall': 1.0,
 'Accuracy': 1.0}

### Question 1: How many false positives and false negatives did your model produce, if any? And why do you think this is?

**Answer**:

The first two models, the _xgboost_ and _pytorch_ models had an accuracy of 100% and therefore no false positives or false negatives. Such a scenario might hint to overfitting. It is possible that the small dataset involved lead to such overfitting.

On the other hand the _sklearn_ model had 3 false positives and 0 false negatives. The _sklearn_ model was not as sophisticated as the two. It was a statistical model of a decision tree unlike the other more sophisticated models.


### Question 2: How did you decide on the type of model to use? 

** Answer**:



----
## EXERCISE: Clean up Resources

After you're done evaluating your model, **delete your model endpoint**. You can do this with a call to `.delete_endpoint()`. You need to show, in this notebook, that the endpoint was deleted. Any other resources, you may delete from the AWS console, and you will find more instructions on cleaning up all your resources, below.

In [ ]:
# uncomment and fill in the line below!
# <name_of_deployed_predictor>.delete_endpoint()


### Deleting S3 bucket

When you are *completely* done with training and testing models, you can also delete your entire S3 bucket. If you do this before you are done training your model, you'll have to recreate your S3 bucket and upload your training data again.

In [ ]:
# deleting bucket, uncomment lines below

# bucket_to_delete = boto3.resource('s3').Bucket(bucket)
# bucket_to_delete.objects.all().delete()

### Deleting all your models and instances

When you are _completely_ done with this project and do **not** ever want to revisit this notebook, you can choose to delete all of your SageMaker notebook instances and models by following [these instructions](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-cleanup.html). Before you delete this notebook instance, I recommend at least downloading a copy and saving it, locally.

---
## Further Directions

There are many ways to improve or add on to this project to expand your learning or make this more of a unique project for you. A few ideas are listed below:
* Train a classifier to predict the *category* (1-3) of plagiarism and not just plagiarized (1) or not (0).
* Utilize a different and larger dataset to see if this model can be extended to other types of plagiarism.
* Use language or character-level analysis to find different (and more) similarity features.
* Write a complete pipeline function that accepts a source text and submitted text file, and classifies the submitted text as plagiarized or not.
* Use API Gateway and a lambda function to deploy your model to a web application.

These are all just options for extending your work. If you've completed all the exercises in this notebook, you've completed a real-world application, and can proceed to submit your project. Great job!